// Code generated by twerge. DO NOT EDIT.
package classes

import twerge "github.com/conneroisu/twerge"

func SetCache() {
	twerge.Default().Handler.SetCache(ClassMapStr)
}

var ClassMapStr = map[string]twerge.CacheValue{
	"-mb-px flex": twerge.CacheValue{
		Generated: "tw-107",
		Merged:    "-mb-px flex",
	},
	"bg-blue-500 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-102",
		Merged:    "bg-blue-500 h-2 rounded-full",
	},
	"bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded-lg transition-colors": twerge.CacheValue{
		Generated: "tw-57",
		Merged:    "hover:bg-blue-600 transition-colors font-medium bg-blue-500 text-white py-2 px-4 rounded-lg",
	},
	"bg-blue-600 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-98",
		Merged:    "rounded-full bg-blue-600 h-2",
	},
	"bg-gray-100 hover:bg-gray-200 text-gray-700 font-medium py-2 px-4 rounded-lg transition-colors": twerge.CacheValue{
		Generated: "tw-61",
		Merged:    "transition-colors text-gray-700 rounded-lg bg-gray-100 hover:bg-gray-200 font-medium py-2 px-4",
	},
	"bg-gray-100 rounded-lg px-4 py-2 focus:outline-none focus:bg-white": twerge.CacheValue{
		Generated: "tw-13",
		Merged:    "focus:bg-white px-4 focus:outline-none rounded-lg py-2 bg-gray-100",
	},
	"bg-gray-100 text-gray-900 flex": twerge.CacheValue{
		Generated: "tw-0",
		Merged:    "bg-gray-100 text-gray-900 flex",
	},
	"bg-gray-50": twerge.CacheValue{
		Generated: "tw-44",
		Merged:    "bg-gray-50",
	},
	"bg-gray-600 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-104",
		Merged:    "h-2 bg-gray-600 rounded-full",
	},
	"bg-green-600 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-99",
		Merged:    "bg-green-600 h-2 rounded-full",
	},
	"bg-orange-600 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-103",
		Merged:    "rounded-full bg-orange-600 h-2",
	},
	"bg-purple-600 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-100",
		Merged:    "rounded-full h-2 bg-purple-600",
	},
	"bg-white divide-y divide-gray-200": twerge.CacheValue{
		Generated: "tw-46",
		Merged:    "bg-white divide-y divide-gray-200",
	},
	"bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200": twerge.CacheValue{
		Generated: "tw-70",
		Merged:    "px-4 border-t py-3 flex items-center border-gray-200 justify-between bg-white",
	},
	"bg-white rounded-lg shadow mb-6": twerge.CacheValue{
		Generated: "tw-105",
		Merged:    "bg-white rounded-lg shadow mb-6",
	},
	"bg-white rounded-lg shadow overflow-hidden": twerge.CacheValue{
		Generated: "tw-62",
		Merged:    "overflow-hidden rounded-lg shadow bg-white",
	},
	"bg-white rounded-lg shadow p-4 mb-6": twerge.CacheValue{
		Generated: "tw-58",
		Merged:    "shadow mb-6 bg-white p-4 rounded-lg",
	},
	"bg-white rounded-lg shadow p-6": twerge.CacheValue{
		Generated: "tw-25",
		Merged:    "bg-white rounded-lg shadow p-6",
	},
	"bg-white rounded-lg shadow": twerge.CacheValue{
		Generated: "tw-39",
		Merged:    "bg-white shadow rounded-lg",
	},
	"bg-white shadow-sm": twerge.CacheValue{
		Generated: "tw-9",
		Merged:    "bg-white shadow-sm",
	},
	"bg-yellow-500 h-2 rounded-full": twerge.CacheValue{
		Generated: "tw-101",
		Merged:    "bg-yellow-500 h-2 rounded-full",
	},
	"block px-4 py-2 text-gray-300 hover:bg-gray-700 hover:text-white transition-colors": twerge.CacheValue{
		Generated: "tw-5",
		Merged:    "hover:bg-gray-700 hover:text-white block px-4 py-2 text-gray-300 transition-colors",
	},
	"block text-sm font-medium text-gray-700 mb-2": twerge.CacheValue{
		Generated: "tw-112",
		Merged:    "font-medium text-gray-700 mb-2 block text-sm",
	},
	"block text-sm font-medium text-gray-700 mb-4": twerge.CacheValue{
		Generated: "tw-118",
		Merged:    "mb-4 block text-sm font-medium text-gray-700",
	},
	"border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:border-blue-500": twerge.CacheValue{
		Generated: "tw-60",
		Merged:    "px-4 focus:border-blue-500 rounded-lg border border-gray-300 focus:outline-none py-2",
	},
	"border-b border-gray-200": twerge.CacheValue{
		Generated: "tw-106",
		Merged:    "border-b border-gray-200",
	},
	"border-b-2 border-indigo-500 py-2 px-4 text-sm font-medium text-indigo-600": twerge.CacheValue{
		Generated: "tw-108",
		Merged:    "px-4 py-2 text-sm border-b-2 border-indigo-500 font-medium text-indigo-600",
	},
	"border-b-2 border-transparent py-2 px-4 text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300": twerge.CacheValue{
		Generated: "tw-109",
		Merged:    "text-gray-500 py-2 px-4 border-transparent text-sm hover:text-gray-700 border-b-2 font-medium hover:border-gray-300",
	},
	"flex flex-wrap items-center justify-between gap-4": twerge.CacheValue{
		Generated: "tw-83",
		Merged:    "flex flex-wrap items-center justify-between gap-4",
	},
	"flex items-center justify-between": twerge.CacheValue{
		Generated: "tw-26",
		Merged:    "flex items-center justify-between",
	},
	"flex items-center space-x-2": twerge.CacheValue{
		Generated: "tw-17",
		Merged:    "flex items-center space-x-2",
	},
	"flex items-center space-x-4": twerge.CacheValue{
		Generated: "tw-14",
		Merged:    "flex items-center space-x-4",
	},
	"flex items-center": twerge.CacheValue{
		Generated: "tw-6",
		Merged:    "items-center flex",
	},
	"flex justify-between items-center mb-6": twerge.CacheValue{
		Generated: "tw-55",
		Merged:    "flex justify-between items-center mb-6",
	},
	"flex justify-between mb-1": twerge.CacheValue{
		Generated: "tw-95",
		Merged:    "flex justify-between mb-1",
	},
	"flex justify-end space-x-3 pt-6": twerge.CacheValue{
		Generated: "tw-122",
		Merged:    "flex justify-end space-x-3 pt-6",
	},
	"flex-1 flex flex-col min-h-screen": twerge.CacheValue{
		Generated: "tw-8",
		Merged:    "flex flex-col min-h-screen flex-1",
	},
	"flex-1 flex justify-between sm:hidden": twerge.CacheValue{
		Generated: "tw-71",
		Merged:    "flex justify-between sm:hidden flex-1",
	},
	"flex-1 overflow-y-auto": twerge.CacheValue{
		Generated: "tw-21",
		Merged:    "overflow-y-auto flex-1",
	},
	"font-medium": twerge.CacheValue{
		Generated: "tw-76",
		Merged:    "font-medium",
	},
	"grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8": twerge.CacheValue{
		Generated: "tw-35",
		Merged:    "lg:grid-cols-2 gap-6 mb-8 grid grid-cols-1",
	},
	"grid grid-cols-1 lg:grid-cols-2 gap-6 mt-8": twerge.CacheValue{
		Generated: "tw-93",
		Merged:    "gap-6 mt-8 grid grid-cols-1 lg:grid-cols-2",
	},
	"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8": twerge.CacheValue{
		Generated: "tw-24",
		Merged:    "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8",
	},
	"grid grid-cols-1 md:grid-cols-4 gap-4": twerge.CacheValue{
		Generated: "tw-59",
		Merged:    "grid-cols-1 md:grid-cols-4 gap-4 grid",
	},
	"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8": twerge.CacheValue{
		Generated: "tw-87",
		Merged:    "mb-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6",
	},
	"h-10 w-10 rounded-full": twerge.CacheValue{
		Generated: "tw-48",
		Merged:    "h-10 w-10 rounded-full",
	},
	"h-10 w-10 text-gray-400": twerge.CacheValue{
		Generated: "tw-115",
		Merged:    "h-10 w-10 text-gray-400",
	},
	"h-12 w-12 text-blue-500": twerge.CacheValue{
		Generated: "tw-29",
		Merged:    "h-12 w-12 text-blue-500",
	},
	"h-12 w-12 text-green-500": twerge.CacheValue{
		Generated: "tw-31",
		Merged:    "h-12 w-12 text-green-500",
	},
	"h-12 w-12 text-purple-500": twerge.CacheValue{
		Generated: "tw-34",
		Merged:    "h-12 w-12 text-purple-500",
	},
	"h-12 w-12 text-yellow-500": twerge.CacheValue{
		Generated: "tw-32",
		Merged:    "h-12 w-12 text-yellow-500",
	},
	"h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded": twerge.CacheValue{
		Generated: "tw-120",
		Merged:    "text-indigo-600 h-4 border-gray-300 rounded w-4 focus:ring-indigo-500",
	},
	"h-4 w-4": twerge.CacheValue{
		Generated: "tw-20",
		Merged:    "h-4 w-4",
	},
	"h-5 w-5 mr-3": twerge.CacheValue{
		Generated: "tw-7",
		Merged:    "w-5 mr-3 h-5",
	},
	"h-5 w-5": twerge.CacheValue{
		Generated: "tw-80",
		Merged:    "h-5 w-5",
	},
	"h-6 w-6": twerge.CacheValue{
		Generated: "tw-12",
		Merged:    "h-6 w-6",
	},
	"h-64 bg-gray-100 rounded flex items-center justify-center": twerge.CacheValue{
		Generated: "tw-37",
		Merged:    "bg-gray-100 rounded flex h-64 justify-center items-center",
	},
	"h-80 bg-gray-100 rounded flex items-center justify-center": twerge.CacheValue{
		Generated: "tw-91",
		Merged:    "h-80 items-center justify-center bg-gray-100 rounded flex",
	},
	"hidden sm:flex-1 sm:flex sm:items-center sm:justify-between": twerge.CacheValue{
		Generated: "tw-74",
		Merged:    "hidden sm:flex-1 sm:flex sm:items-center sm:justify-between",
	},
	"min-w-full": twerge.CacheValue{
		Generated: "tw-43",
		Merged:    "min-w-full",
	},
	"ml-2 text-sm text-gray-700": twerge.CacheValue{
		Generated: "tw-121",
		Merged:    "text-gray-700 ml-2 text-sm",
	},
	"ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50": twerge.CacheValue{
		Generated: "tw-73",
		Merged:    "text-gray-700 border ml-3 inline-flex relative items-center py-2 bg-white px-4 text-sm font-medium rounded-md hover:bg-gray-50 border-gray-300",
	},
	"ml-4": twerge.CacheValue{
		Generated: "tw-49",
		Merged:    "ml-4",
	},
	"mt-8": twerge.CacheValue{
		Generated: "tw-4",
		Merged:    "mt-8",
	},
	"overflow-x-auto": twerge.CacheValue{
		Generated: "tw-42",
		Merged:    "overflow-x-auto",
	},
	"p-4": twerge.CacheValue{
		Generated: "tw-2",
		Merged:    "p-4",
	},
	"p-6": twerge.CacheValue{
		Generated: "tw-22",
		Merged:    "p-6",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800": twerge.CacheValue{
		Generated: "tw-67",
		Merged:    "px-2 bg-blue-100 text-blue-800 inline-flex leading-5 font-semibold rounded-full text-xs",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800": twerge.CacheValue{
		Generated: "tw-68",
		Merged:    "font-semibold leading-5 inline-flex rounded-full bg-gray-100 text-gray-800 text-xs px-2",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800": twerge.CacheValue{
		Generated: "tw-53",
		Merged:    "rounded-full px-2 inline-flex font-semibold text-xs leading-5 bg-green-100 text-green-800",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-purple-100 text-purple-800": twerge.CacheValue{
		Generated: "tw-63",
		Merged:    "leading-5 font-semibold bg-purple-100 px-2 inline-flex text-xs rounded-full text-purple-800",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800": twerge.CacheValue{
		Generated: "tw-54",
		Merged:    "px-2 inline-flex rounded-full leading-5 font-semibold bg-red-100 text-red-800 text-xs",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800": twerge.CacheValue{
		Generated: "tw-69",
		Merged:    "inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800 px-2",
	},
	"px-4 py-2 bg-indigo-600 border border-transparent rounded-md text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500": twerge.CacheValue{
		Generated: "tw-123",
		Merged:    "font-medium text-white bg-indigo-600 border-transparent px-4 py-2 border hover:bg-indigo-700 focus:ring-2 text-sm focus:ring-offset-2 focus:ring-indigo-500 rounded-md focus:outline-none",
	},
	"px-4 py-2 bg-white border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500": twerge.CacheValue{
		Generated: "tw-116",
		Merged:    "focus:outline-none font-medium hover:bg-gray-50 py-2 border text-sm text-gray-700 rounded-md focus:ring-indigo-500 px-4 bg-white border-gray-300 focus:ring-2 focus:ring-offset-2",
	},
	"px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500": twerge.CacheValue{
		Generated: "tw-84",
		Merged:    "border-gray-300 rounded-lg font-medium hover:bg-gray-50 focus:ring-2 focus:ring-offset-2 bg-white py-2 border focus:outline-none focus:ring-indigo-500 px-4 text-gray-700 text-sm",
	},
	"px-4 py-2 text-sm font-medium text-indigo-600 bg-white border border-indigo-600 rounded-lg hover:bg-indigo-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500": twerge.CacheValue{
		Generated: "tw-86",
		Merged:    "px-4 hover:bg-indigo-50 focus:outline-none text-sm bg-white focus:ring-offset-2 py-2 focus:ring-2 font-medium rounded-lg text-indigo-600 border border-indigo-600 focus:ring-indigo-500",
	},
	"px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500": twerge.CacheValue{
		Generated: "tw-85",
		Merged:    "focus:ring-indigo-500 py-2 rounded-lg hover:bg-indigo-700 focus:outline-none text-white focus:ring-offset-2 px-4 text-sm focus:ring-2 font-medium bg-indigo-600",
	},
	"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider": twerge.CacheValue{
		Generated: "tw-45",
		Merged:    "px-6 py-3 text-left font-medium text-gray-500 tracking-wider text-xs uppercase",
	},
	"px-6 py-4 border-b border-gray-200": twerge.CacheValue{
		Generated: "tw-40",
		Merged:    "border-b border-gray-200 py-4 px-6",
	},
	"px-6 py-4 flex justify-between items-center": twerge.CacheValue{
		Generated: "tw-10",
		Merged:    "justify-between px-6 py-4 flex items-center",
	},
	"px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900": twerge.CacheValue{
		Generated: "tw-92",
		Merged:    "font-medium whitespace-nowrap text-sm text-gray-900 px-6 py-4",
	},
	"px-6 py-4 whitespace-nowrap text-sm font-medium": twerge.CacheValue{
		Generated: "tw-64",
		Merged:    "px-6 font-medium py-4 whitespace-nowrap text-sm",
	},
	"px-6 py-4 whitespace-nowrap text-sm text-gray-500": twerge.CacheValue{
		Generated: "tw-52",
		Merged:    "whitespace-nowrap py-4 text-sm text-gray-500 px-6",
	},
	"px-6 py-4 whitespace-nowrap": twerge.CacheValue{
		Generated: "tw-47",
		Merged:    "py-4 whitespace-nowrap px-6",
	},
	"relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50": twerge.CacheValue{
		Generated: "tw-78",
		Merged:    "border border-gray-300 bg-white text-gray-500 py-2 relative items-center font-medium text-sm inline-flex px-2 rounded-l-md hover:bg-gray-50",
	},
	"relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50": twerge.CacheValue{
		Generated: "tw-82",
		Merged:    "items-center px-2 py-2 border-gray-300 text-gray-500 text-sm hover:bg-gray-50 relative border inline-flex rounded-r-md font-medium bg-white",
	},
	"relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50": twerge.CacheValue{
		Generated: "tw-81",
		Merged:    "bg-white hover:bg-gray-50 inline-flex items-center border border-gray-300 text-sm relative px-4 py-2 font-medium text-gray-700",
	},
	"relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50": twerge.CacheValue{
		Generated: "tw-72",
		Merged:    "bg-white hover:bg-gray-50 font-medium rounded-md inline-flex items-center border-gray-300 text-sm px-4 py-2 text-gray-700 relative border",
	},
	"relative z-0 inline-flex rounded-md shadow-sm -space-x-px": twerge.CacheValue{
		Generated: "tw-77",
		Merged:    "inline-flex -space-x-px shadow-sm relative z-0 rounded-md",
	},
	"relative": twerge.CacheValue{
		Generated: "tw-16",
		Merged:    "relative",
	},
	"space-y-3": twerge.CacheValue{
		Generated: "tw-119",
		Merged:    "space-y-3",
	},
	"space-y-4": twerge.CacheValue{
		Generated: "tw-94",
		Merged:    "space-y-4",
	},
	"space-y-6": twerge.CacheValue{
		Generated: "tw-111",
		Merged:    "space-y-6",
	},
	"sr-only": twerge.CacheValue{
		Generated: "tw-79",
		Merged:    "sr-only",
	},
	"text-2xl font-bold text-gray-800": twerge.CacheValue{
		Generated: "tw-28",
		Merged:    "text-gray-800 text-2xl font-bold",
	},
	"text-3xl font-bold text-gray-800 mb-6": twerge.CacheValue{
		Generated: "tw-23",
		Merged:    "font-bold text-gray-800 mb-6 text-3xl",
	},
	"text-3xl font-bold text-gray-800": twerge.CacheValue{
		Generated: "tw-56",
		Merged:    "font-bold text-gray-800 text-3xl",
	},
	"text-gray-500 focus:outline-none lg:hidden": twerge.CacheValue{
		Generated: "tw-11",
		Merged:    "lg:hidden text-gray-500 focus:outline-none",
	},
	"text-gray-500 hover:text-gray-700": twerge.CacheValue{
		Generated: "tw-15",
		Merged:    "text-gray-500 hover:text-gray-700",
	},
	"text-gray-500": twerge.CacheValue{
		Generated: "tw-38",
		Merged:    "text-gray-500",
	},
	"text-gray-700": twerge.CacheValue{
		Generated: "tw-19",
		Merged:    "text-gray-700",
	},
	"text-indigo-600 hover:text-indigo-900 mr-4": twerge.CacheValue{
		Generated: "tw-65",
		Merged:    "text-indigo-600 hover:text-indigo-900 mr-4",
	},
	"text-lg font-semibold text-gray-800 mb-4": twerge.CacheValue{
		Generated: "tw-36",
		Merged:    "text-lg font-semibold text-gray-800 mb-4",
	},
	"text-lg font-semibold text-gray-800 mb-6": twerge.CacheValue{
		Generated: "tw-110",
		Merged:    "text-lg font-semibold text-gray-800 mb-6",
	},
	"text-lg font-semibold text-gray-800": twerge.CacheValue{
		Generated: "tw-41",
		Merged:    "text-lg font-semibold text-gray-800",
	},
	"text-red-600 hover:text-red-900": twerge.CacheValue{
		Generated: "tw-66",
		Merged:    "text-red-600 hover:text-red-900",
	},
	"text-sm font-medium text-gray-600 mb-2": twerge.CacheValue{
		Generated: "tw-88",
		Merged:    "text-sm font-medium text-gray-600 mb-2",
	},
	"text-sm font-medium text-gray-700": twerge.CacheValue{
		Generated: "tw-96",
		Merged:    "font-medium text-gray-700 text-sm",
	},
	"text-sm font-medium text-gray-900": twerge.CacheValue{
		Generated: "tw-50",
		Merged:    "text-gray-900 text-sm font-medium",
	},
	"text-sm text-gray-500": twerge.CacheValue{
		Generated: "tw-51",
		Merged:    "text-sm text-gray-500",
	},
	"text-sm text-gray-600": twerge.CacheValue{
		Generated: "tw-27",
		Merged:    "text-sm text-gray-600",
	},
	"text-sm text-gray-700": twerge.CacheValue{
		Generated: "tw-75",
		Merged:    "text-gray-700 text-sm",
	},
	"text-sm text-green-600 mt-1": twerge.CacheValue{
		Generated: "tw-89",
		Merged:    "text-sm text-green-600 mt-1",
	},
	"text-sm text-green-600 mt-2": twerge.CacheValue{
		Generated: "tw-30",
		Merged:    "text-green-600 mt-2 text-sm",
	},
	"text-sm text-red-600 mt-1": twerge.CacheValue{
		Generated: "tw-90",
		Merged:    "text-sm text-red-600 mt-1",
	},
	"text-sm text-red-600 mt-2": twerge.CacheValue{
		Generated: "tw-33",
		Merged:    "text-red-600 mt-2 text-sm",
	},
	"text-white text-2xl font-bold": twerge.CacheValue{
		Generated: "tw-3",
		Merged:    "text-white text-2xl font-bold",
	},
	"text-xs text-gray-500 mt-1": twerge.CacheValue{
		Generated: "tw-117",
		Merged:    "text-xs text-gray-500 mt-1",
	},
	"w-20 h-20 bg-gray-200 rounded-lg flex items-center justify-center": twerge.CacheValue{
		Generated: "tw-114",
		Merged:    "w-20 bg-gray-200 justify-center h-20 flex items-center rounded-lg",
	},
	"w-64 bg-gray-800 min-h-screen": twerge.CacheValue{
		Generated: "tw-1",
		Merged:    "w-64 bg-gray-800 min-h-screen",
	},
	"w-8 h-8 rounded-full": twerge.CacheValue{
		Generated: "tw-18",
		Merged:    "h-8 rounded-full w-8",
	},
	"w-full bg-gray-200 rounded-full h-2": twerge.CacheValue{
		Generated: "tw-97",
		Merged:    "bg-gray-200 h-2 rounded-full w-full",
	},
	"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500": twerge.CacheValue{
		Generated: "tw-113",
		Merged:    "border px-3 py-2 rounded-md focus:ring-indigo-500 focus:border-indigo-500 focus:outline-none w-full border-gray-300",
	},
}
