// Code generated by twerge. DO NOT EDIT.
package classes

import twerge "github.com/conneroisu/twerge"

func SetCache() {
	twerge.Default().Handler.SetCache(ClassMapStr)
}

var ClassMapStr = map[string]twerge.CacheValue{
	"-translate-x-full md:translate-x-0": twerge.CacheValue{
		Generated: "tw-2",
		Merged:    "-translate-x-full md:translate-x-0",
	},
	"absolute left-3 top-2.5 w-5 h-5 text-gray-400": twerge.CacheValue{
		Generated: "tw-22",
		Merged:    "absolute left-3 top-2.5 w-5 h-5 text-gray-400",
	},
	"absolute top-0 right-0 w-2 h-2 bg-red-500 rounded-full": twerge.CacheValue{
		Generated: "tw-24",
		Merged:    "absolute h-2 bg-red-500 w-2 rounded-full top-0 right-0",
	},
	"bg-gray-50 dark:bg-gray-900": twerge.CacheValue{
		Generated: "tw-42",
		Merged:    "bg-gray-50 dark:bg-gray-900",
	},
	"bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200": twerge.CacheValue{
		Generated: "tw-54",
		Merged:    "dark:text-green-200 bg-green-100 text-green-800 dark:bg-green-900",
	},
	"bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200": twerge.CacheValue{
		Generated: "tw-55",
		Merged:    "text-red-800 dark:bg-red-900 dark:text-red-200 bg-red-100",
	},
	"bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700": twerge.CacheValue{
		Generated: "tw-15",
		Merged:    "bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700",
	},
	"bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700": twerge.CacheValue{
		Generated: "tw-51",
		Merged:    "bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700",
	},
	"bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6 border border-gray-200 dark:border-gray-700 hover:shadow-md transition-shadow duration-200": twerge.CacheValue{
		Generated: "tw-30",
		Merged:    "duration-200 rounded-lg dark:border-gray-700 bg-white shadow-sm dark:bg-gray-800 border-gray-200 p-6 border hover:shadow-md transition-shadow",
	},
	"flex h-screen overflow-hidden": twerge.CacheValue{
		Generated: "tw-1",
		Merged:    "flex h-screen overflow-hidden",
	},
	"flex items-center justify-between h-16 px-6 border-b border-gray-200 dark:border-gray-700": twerge.CacheValue{
		Generated: "tw-6",
		Merged:    "dark:border-gray-700 flex items-center justify-between h-16 border-gray-200 px-6 border-b",
	},
	"flex items-center justify-between h-16 px-6": twerge.CacheValue{
		Generated: "tw-16",
		Merged:    "flex items-center justify-between h-16 px-6",
	},
	"flex items-center justify-between": twerge.CacheValue{
		Generated: "tw-31",
		Merged:    "flex items-center justify-between",
	},
	"flex items-center px-4 py-2 text-sm font-medium rounded-lg transition-colors duration-200 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-200": twerge.CacheValue{
		Generated: "tw-10",
		Merged:    "bg-blue-100 duration-200 px-4 items-center py-2 text-blue-700 transition-colors dark:text-blue-200 flex text-sm rounded-lg font-medium dark:bg-blue-900",
	},
	"flex items-center px-4 py-2 text-sm font-medium rounded-lg transition-colors duration-200 text-gray-700 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-800": twerge.CacheValue{
		Generated: "tw-12",
		Merged:    "dark:hover:bg-gray-800 items-center font-medium duration-200 px-4 py-2 text-gray-700 text-sm rounded-lg hover:bg-gray-100 flex transition-colors dark:text-gray-200",
	},
	"flex items-center space-x-1": twerge.CacheValue{
		Generated: "tw-46",
		Merged:    "flex items-center space-x-1",
	},
	"flex items-center space-x-3 p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors duration-200": twerge.CacheValue{
		Generated: "tw-25",
		Merged:    "dark:hover:bg-gray-700 transition-colors rounded-lg space-x-3 p-2 duration-200 flex hover:bg-gray-100 items-center",
	},
	"flex items-center space-x-4": twerge.CacheValue{
		Generated: "tw-19",
		Merged:    "flex items-center space-x-4",
	},
	"flex-1 flex flex-col overflow-hidden": twerge.CacheValue{
		Generated: "tw-14",
		Merged:    "flex-col flex overflow-hidden flex-1",
	},
	"flex-1 overflow-y-auto p-4 lg:p-6": twerge.CacheValue{
		Generated: "tw-28",
		Merged:    "flex-1 p-4 overflow-y-auto lg:p-6",
	},
	"flex-1 overflow-y-auto py-4": twerge.CacheValue{
		Generated: "tw-8",
		Merged:    "flex-1 overflow-y-auto py-4",
	},
	"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 lg:gap-6 xl:gap-8": twerge.CacheValue{
		Generated: "tw-29",
		Merged:    "grid grid-cols-1 lg:grid-cols-3 xl:grid-cols-4 gap-4 lg:gap-6 sm:grid-cols-2 xl:gap-8",
	},
	"h-4 w-4 transition-transform tw-48": twerge.CacheValue{
		Generated: "tw-50",
		Merged:    "tw-48 h-4 w-4 transition-transform",
	},
	"h-4 w-4 transition-transform tw-49": twerge.CacheValue{
		Generated: "tw-59",
		Merged:    "tw-49 h-4 w-4 transition-transform",
	},
	"h-full flex flex-col": twerge.CacheValue{
		Generated: "tw-5",
		Merged:    "flex-col h-full flex",
	},
	"hidden md:block relative": twerge.CacheValue{
		Generated: "tw-20",
		Merged:    "md:block relative hidden",
	},
	"hidden md:block text-sm font-medium text-gray-700 dark:text-gray-300": twerge.CacheValue{
		Generated: "tw-27",
		Merged:    "dark:text-gray-300 hidden md:block text-sm font-medium text-gray-700",
	},
	"hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors duration-200": twerge.CacheValue{
		Generated: "tw-52",
		Merged:    "duration-200 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors",
	},
	"inline-flex px-2 text-xs font-semibold leading-5 rounded-full tw-54": twerge.CacheValue{
		Generated: "tw-56",
		Merged:    "tw-54 px-2 font-semibold rounded-full text-xs leading-5 inline-flex",
	},
	"inline-flex px-2 text-xs font-semibold leading-5 rounded-full tw-55": twerge.CacheValue{
		Generated: "tw-57",
		Merged:    "tw-55 px-2 rounded-full text-xs font-semibold inline-flex leading-5",
	},
	"md:hidden p-2 rounded-lg text-gray-500 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 transition-colors duration-200": twerge.CacheValue{
		Generated: "tw-17",
		Merged:    "dark:hover:bg-gray-700 transition-colors dark:text-gray-400 duration-200 rounded-lg p-2 hover:bg-gray-100 md:hidden text-gray-500",
	},
	"min-h-screen bg-gray-50 dark:bg-gray-900": twerge.CacheValue{
		Generated: "tw-0",
		Merged:    "dark:bg-gray-900 min-h-screen bg-gray-50",
	},
	"min-w-full divide-y divide-gray-200 dark:divide-gray-700": twerge.CacheValue{
		Generated: "tw-41",
		Merged:    "min-w-full divide-y divide-gray-200 dark:divide-gray-700",
	},
	"ml-auto h-4 w-4 transition-transform group-hover:rotate-90": twerge.CacheValue{
		Generated: "tw-13",
		Merged:    "group-hover:rotate-90 ml-auto h-4 w-4 transition-transform",
	},
	"mr-3 h-5 w-5": twerge.CacheValue{
		Generated: "tw-11",
		Merged:    "mr-3 h-5 w-5",
	},
	"mt-2 text-2xl font-bold text-gray-900 dark:text-white": twerge.CacheValue{
		Generated: "tw-36",
		Merged:    "mt-2 text-2xl font-bold text-gray-900 dark:text-white",
	},
	"mt-8 grid grid-cols-1 lg:grid-cols-2 gap-6": twerge.CacheValue{
		Generated: "tw-38",
		Merged:    "lg:grid-cols-2 gap-6 mt-8 grid grid-cols-1",
	},
	"overflow-x-auto bg-white dark:bg-gray-800 shadow-lg rounded-lg": twerge.CacheValue{
		Generated: "tw-40",
		Merged:    "overflow-x-auto bg-white rounded-lg shadow-lg dark:bg-gray-800",
	},
	"p-2 rounded-lg text-gray-500 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 transition-colors duration-200 relative": twerge.CacheValue{
		Generated: "tw-23",
		Merged:    "dark:text-gray-400 hover:bg-gray-100 relative p-2 dark:hover:bg-gray-700 rounded-lg duration-200 text-gray-500 transition-colors",
	},
	"px-6 py-3 text-left text-xs font-medium uppercase tracking-wider cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 tw-43": twerge.CacheValue{
		Generated: "tw-47",
		Merged:    "tw-43 px-6 font-medium uppercase dark:hover:bg-gray-700 text-left text-xs hover:bg-gray-100 tracking-wider py-3 cursor-pointer",
	},
	"px-6 py-3 text-left text-xs font-medium uppercase tracking-wider cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 tw-44": twerge.CacheValue{
		Generated: "tw-45",
		Merged:    "tw-44 py-3 text-xs text-left font-medium cursor-pointer dark:hover:bg-gray-700 px-6 uppercase tracking-wider hover:bg-gray-100",
	},
	"px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white": twerge.CacheValue{
		Generated: "tw-53",
		Merged:    "px-6 py-4 text-gray-900 whitespace-nowrap text-sm dark:text-white",
	},
	"rotate-0": twerge.CacheValue{
		Generated: "tw-49",
		Merged:    "rotate-0",
	},
	"rotate-180": twerge.CacheValue{
		Generated: "tw-48",
		Merged:    "rotate-180",
	},
	"space-y-1 px-3": twerge.CacheValue{
		Generated: "tw-9",
		Merged:    "space-y-1 px-3",
	},
	"text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20": twerge.CacheValue{
		Generated: "tw-43",
		Merged:    "text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20",
	},
	"text-gray-500 dark:text-gray-400": twerge.CacheValue{
		Generated: "tw-44",
		Merged:    "text-gray-500 dark:text-gray-400",
	},
	"text-green-600 dark:text-green-400": twerge.CacheValue{
		Generated: "tw-33",
		Merged:    "text-green-600 dark:text-green-400",
	},
	"text-lg font-semibold text-gray-900 dark:text-white mb-4": twerge.CacheValue{
		Generated: "tw-39",
		Merged:    "text-lg font-semibold text-gray-900 dark:text-white mb-4",
	},
	"text-red-600 dark:text-red-400": twerge.CacheValue{
		Generated: "tw-34",
		Merged:    "text-red-600 dark:text-red-400",
	},
	"text-sm font-medium text-gray-500 dark:text-gray-400": twerge.CacheValue{
		Generated: "tw-32",
		Merged:    "text-sm font-medium text-gray-500 dark:text-gray-400",
	},
	"text-sm font-medium tw-33": twerge.CacheValue{
		Generated: "tw-35",
		Merged:    "tw-33 text-sm font-medium",
	},
	"text-sm font-medium tw-34": twerge.CacheValue{
		Generated: "tw-37",
		Merged:    "tw-34 text-sm font-medium",
	},
	"text-xl font-bold text-gray-900 dark:text-white": twerge.CacheValue{
		Generated: "tw-7",
		Merged:    "font-bold text-gray-900 dark:text-white text-xl",
	},
	"translate-x-0": twerge.CacheValue{
		Generated: "tw-3",
		Merged:    "translate-x-0",
	},
	"w-6 h-6": twerge.CacheValue{
		Generated: "tw-18",
		Merged:    "w-6 h-6",
	},
	"w-64 lg:w-80 xl:w-96 md:translate-x-0 tw-2 transition-transform duration-300 ease-in-out bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700": twerge.CacheValue{
		Generated: "tw-58",
		Merged:    "tw-2 w-64 xl:w-96 duration-300 ease-in-out dark:bg-gray-900 dark:border-gray-700 md:translate-x-0 transition-transform bg-white lg:w-80 border-r border-gray-200",
	},
	"w-64 lg:w-80 xl:w-96 md:translate-x-0 tw-3 transition-transform duration-300 ease-in-out bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700": twerge.CacheValue{
		Generated: "tw-4",
		Merged:    "tw-3 w-64 transition-transform ease-in-out dark:border-gray-700 border-r lg:w-80 xl:w-96 md:translate-x-0 duration-300 border-gray-200 bg-white dark:bg-gray-900",
	},
	"w-64 px-4 py-2 pl-10 text-sm border rounded-lg bg-gray-50 dark:bg-gray-900 border-gray-300 dark:border-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent": twerge.CacheValue{
		Generated: "tw-21",
		Merged:    "border-gray-300 focus:ring-blue-500 px-4 pl-10 focus:border-transparent dark:bg-gray-900 focus:outline-none focus:ring-2 text-sm w-64 border bg-gray-50 dark:border-gray-600 py-2 rounded-lg",
	},
	"w-8 h-8 rounded-full": twerge.CacheValue{
		Generated: "tw-26",
		Merged:    "w-8 h-8 rounded-full",
	},
}
