// Code generated by twerge. DO NOT EDIT.
package classes

import twerge "github.com/conneroisu/twerge"

func SetCache() {
	twerge.Default().Handler.SetCache(ClassMapStr)
}

var ClassMapStr = map[string]twerge.CacheValue{
	"bg-gray-100 text-gray-900 flex flex-col min-h-screen": twerge.CacheValue{
		Generated: "tw-0",
		Merged:    "bg-gray-100 text-gray-900 flex flex-col min-h-screen",
	},
	"bg-gray-50": twerge.CacheValue{
		Generated: "tw-21",
		Merged:    "bg-gray-50",
	},
	"bg-gray-800 text-white py-4": twerge.CacheValue{
		Generated: "tw-30",
		Merged:    "py-4 bg-gray-800 text-white",
	},
	"bg-green-100 text-green-800 text-xs font-semibold px-2 py-1 rounded": twerge.CacheValue{
		Generated: "tw-15",
		Merged:    "text-green-800 py-1 rounded px-2 bg-green-100 text-xs font-semibold",
	},
	"bg-indigo-700 text-white shadow-lg": twerge.CacheValue{
		Generated: "tw-1",
		Merged:    "bg-indigo-700 text-white shadow-lg",
	},
	"bg-red-100 text-red-800 text-xs font-semibold px-2 py-1 rounded": twerge.CacheValue{
		Generated: "tw-18",
		Merged:    "text-xs font-semibold py-1 text-red-800 px-2 rounded bg-red-100",
	},
	"bg-white divide-y divide-gray-200": twerge.CacheValue{
		Generated: "tw-23",
		Merged:    "bg-white divide-y divide-gray-200",
	},
	"bg-white rounded-lg shadow-md overflow-hidden": twerge.CacheValue{
		Generated: "tw-19",
		Merged:    "bg-white rounded-lg shadow-md overflow-hidden",
	},
	"bg-white rounded-lg shadow-md p-6": twerge.CacheValue{
		Generated: "tw-12",
		Merged:    "shadow-md rounded-lg bg-white p-6",
	},
	"container mx-auto px-4 py-3 flex justify-between items-center": twerge.CacheValue{
		Generated: "tw-2",
		Merged:    "flex justify-between items-center py-3 container mx-auto px-4",
	},
	"container mx-auto px-4 py-6 flex-grow": twerge.CacheValue{
		Generated: "tw-8",
		Merged:    "flex-grow py-6 container mx-auto px-4",
	},
	"container mx-auto px-4 text-center text-sm": twerge.CacheValue{
		Generated: "tw-31",
		Merged:    "px-4 mx-auto text-center text-sm container",
	},
	"flex items-center justify-between": twerge.CacheValue{
		Generated: "tw-13",
		Merged:    "flex items-center justify-between",
	},
	"flex items-center space-x-2": twerge.CacheValue{
		Generated: "tw-3",
		Merged:    "flex items-center space-x-2",
	},
	"flex space-x-6": twerge.CacheValue{
		Generated: "tw-6",
		Merged:    "space-x-6 flex",
	},
	"grid grid-cols-1 md:grid-cols-3 gap-6": twerge.CacheValue{
		Generated: "tw-11",
		Merged:    "grid grid-cols-1 md:grid-cols-3 gap-6",
	},
	"h-8 w-8": twerge.CacheValue{
		Generated: "tw-4",
		Merged:    "h-8 w-8",
	},
	"hover:text-indigo-200 transition-colors": twerge.CacheValue{
		Generated: "tw-7",
		Merged:    "transition-colors hover:text-indigo-200",
	},
	"mb-6": twerge.CacheValue{
		Generated: "tw-9",
		Merged:    "mb-6",
	},
	"min-w-full divide-y divide-gray-200": twerge.CacheValue{
		Generated: "tw-20",
		Merged:    "min-w-full divide-y divide-gray-200",
	},
	"mt-4 text-sm text-gray-500": twerge.CacheValue{
		Generated: "tw-17",
		Merged:    "text-sm text-gray-500 mt-4",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800": twerge.CacheValue{
		Generated: "tw-29",
		Merged:    "rounded-full text-xs text-gray-800 inline-flex font-semibold bg-gray-100 px-2 leading-5",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800": twerge.CacheValue{
		Generated: "tw-27",
		Merged:    "inline-flex font-semibold text-xs rounded-full text-green-800 leading-5 bg-green-100 px-2",
	},
	"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800": twerge.CacheValue{
		Generated: "tw-28",
		Merged:    "leading-5 bg-yellow-100 text-yellow-800 px-2 text-xs rounded-full inline-flex font-semibold",
	},
	"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider": twerge.CacheValue{
		Generated: "tw-22",
		Merged:    "text-left font-medium text-gray-500 px-6 py-3 text-xs uppercase tracking-wider",
	},
	"px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900": twerge.CacheValue{
		Generated: "tw-24",
		Merged:    "text-gray-900 px-6 py-4 whitespace-nowrap font-medium text-sm",
	},
	"px-6 py-4 whitespace-nowrap text-sm text-gray-500": twerge.CacheValue{
		Generated: "tw-25",
		Merged:    "px-6 py-4 whitespace-nowrap text-sm text-gray-500",
	},
	"px-6 py-4 whitespace-nowrap": twerge.CacheValue{
		Generated: "tw-26",
		Merged:    "py-4 whitespace-nowrap px-6",
	},
	"text-2xl font-bold text-gray-800 mb-4": twerge.CacheValue{
		Generated: "tw-10",
		Merged:    "text-2xl font-bold text-gray-800 mb-4",
	},
	"text-3xl font-bold text-gray-800 mt-2": twerge.CacheValue{
		Generated: "tw-16",
		Merged:    "mt-2 text-3xl font-bold text-gray-800",
	},
	"text-gray-500 text-sm font-medium": twerge.CacheValue{
		Generated: "tw-14",
		Merged:    "text-gray-500 text-sm font-medium",
	},
	"text-indigo-300 hover:text-indigo-100": twerge.CacheValue{
		Generated: "tw-32",
		Merged:    "text-indigo-300 hover:text-indigo-100",
	},
	"text-xl font-bold": twerge.CacheValue{
		Generated: "tw-5",
		Merged:    "text-xl font-bold",
	},
}
