[book]
authors = [
    "conneroisu"
]
language = "en"
multilingual = false
src = "src"
title = "twerge"

[preprocessor.cmdrun]
command = "mdbook-cmdrun"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/conneroisu/twerge"
git-branch = "main"
open-on-text = """
<hr style="margin-top: 5em;" />
Found an issue? [Edit this page on GitHub.]
"""
