// Code generated by twerge. DO NOT EDIT.
package classes

import twerge "github.com/conneroisu/twerge"

func SetCache() {
	twerge.Default().Handler.SetCache(ClassMapStr)
}

var ClassMapStr = map[string]twerge.CacheValue{
	"bg-blue-600 text-white px-6 py-3 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors": twerge.CacheValue{
		Generated: "tw-30",
		Merged:    "rounded-md focus:outline-none focus:ring-opacity-50 bg-blue-600 py-3 focus:ring-2 focus:ring-blue-500 text-white hover:bg-blue-700 px-6 transition-colors",
	},
	"bg-gray-100 border-t border-gray-200 py-8 mt-12": twerge.CacheValue{
		Generated: "tw-53",
		Merged:    "border-t border-gray-200 py-8 mt-12 bg-gray-100",
	},
	"bg-gray-100 p-4 rounded overflow-x-auto": twerge.CacheValue{
		Generated: "tw-34",
		Merged:    "overflow-x-auto p-4 bg-gray-100 rounded",
	},
	"bg-white border-b border-gray-200": twerge.CacheValue{
		Generated: "tw-45",
		Merged:    "bg-white border-b border-gray-200",
	},
	"bg-white rounded-lg shadow-md overflow-hidden": twerge.CacheValue{
		Generated: "tw-4",
		Merged:    "shadow-md bg-white rounded-lg overflow-hidden",
	},
	"bg-white text-gray-900 flex flex-col min-h-screen": twerge.CacheValue{
		Generated: "tw-44",
		Merged:    "flex flex-col min-h-screen bg-white text-gray-900",
	},
	"block text-sm font-medium text-gray-700 mb-1": twerge.CacheValue{
		Generated: "tw-28",
		Merged:    "text-gray-700 mb-1 block text-sm font-medium",
	},
	"border-b border-gray-200 pb-8": twerge.CacheValue{
		Generated: "tw-12",
		Merged:    "pb-8 border-b border-gray-200",
	},
	"container mx-auto px-4 py-4 flex justify-between items-center": twerge.CacheValue{
		Generated: "tw-46",
		Merged:    "justify-between items-center container py-4 flex mx-auto px-4",
	},
	"container mx-auto px-4 py-8 flex-grow": twerge.CacheValue{
		Generated: "tw-51",
		Merged:    "flex-grow container px-4 py-8 mx-auto",
	},
	"container mx-auto px-4": twerge.CacheValue{
		Generated: "tw-54",
		Merged:    "container mx-auto px-4",
	},
	"flex flex-col md:flex-row justify-between items-center": twerge.CacheValue{
		Generated: "tw-55",
		Merged:    "flex flex-col md:flex-row justify-between items-center",
	},
	"flex flex-wrap gap-2": twerge.CacheValue{
		Generated: "tw-37",
		Merged:    "flex flex-wrap gap-2",
	},
	"flex items-center space-x-2": twerge.CacheValue{
		Generated: "tw-47",
		Merged:    "flex items-center space-x-2",
	},
	"flex items-center text-gray-600 text-sm mb-4": twerge.CacheValue{
		Generated: "tw-15",
		Merged:    "mb-4 flex items-center text-gray-600 text-sm",
	},
	"flex items-center text-gray-600 text-sm": twerge.CacheValue{
		Generated: "tw-33",
		Merged:    "flex items-center text-gray-600 text-sm",
	},
	"flex items-start mt-8 bg-gray-50 p-6 rounded-lg": twerge.CacheValue{
		Generated: "tw-20",
		Merged:    "flex items-start mt-8 bg-gray-50 p-6 rounded-lg",
	},
	"flex items-start": twerge.CacheValue{
		Generated: "tw-40",
		Merged:    "flex items-start",
	},
	"flex space-x-4": twerge.CacheValue{
		Generated: "tw-59",
		Merged:    "flex space-x-4",
	},
	"flex space-x-6": twerge.CacheValue{
		Generated: "tw-50",
		Merged:    "flex space-x-6",
	},
	"flex-shrink-0 mr-4": twerge.CacheValue{
		Generated: "tw-21",
		Merged:    "flex-shrink-0 mr-4",
	},
	"font-bold text-xl": twerge.CacheValue{
		Generated: "tw-23",
		Merged:    "text-xl font-bold",
	},
	"font-medium": twerge.CacheValue{
		Generated: "tw-42",
		Merged:    "font-medium",
	},
	"grid grid-cols-1 md:grid-cols-2 gap-8": twerge.CacheValue{
		Generated: "tw-3",
		Merged:    "grid grid-cols-1 md:grid-cols-2 gap-8",
	},
	"h-8 w-8 text-blue-600": twerge.CacheValue{
		Generated: "tw-48",
		Merged:    "h-8 w-8 text-blue-600",
	},
	"hover:text-blue-600 transition-colors": twerge.CacheValue{
		Generated: "tw-14",
		Merged:    "hover:text-blue-600 transition-colors",
	},
	"max-w-4xl mx-auto": twerge.CacheValue{
		Generated: "tw-52",
		Merged:    "max-w-4xl mx-auto",
	},
	"mb-4 md:mb-0": twerge.CacheValue{
		Generated: "tw-56",
		Merged:    "mb-4 md:mb-0",
	},
	"mb-8": twerge.CacheValue{
		Generated: "tw-31",
		Merged:    "mb-8",
	},
	"mt-2": twerge.CacheValue{
		Generated: "tw-25",
		Merged:    "mt-2",
	},
	"mt-6 text-center text-gray-600 text-sm": twerge.CacheValue{
		Generated: "tw-61",
		Merged:    "mt-6 text-center text-gray-600 text-sm",
	},
	"mt-8 bg-gray-50 p-6 rounded-lg": twerge.CacheValue{
		Generated: "tw-39",
		Merged:    "bg-gray-50 p-6 rounded-lg mt-8",
	},
	"mt-8 pt-8 border-t border-gray-200": twerge.CacheValue{
		Generated: "tw-35",
		Merged:    "mt-8 pt-8 border-t border-gray-200",
	},
	"mx-2": twerge.CacheValue{
		Generated: "tw-16",
		Merged:    "mx-2",
	},
	"p-6": twerge.CacheValue{
		Generated: "tw-6",
		Merged:    "p-6",
	},
	"prose max-w-none": twerge.CacheValue{
		Generated: "tw-18",
		Merged:    "prose max-w-none",
	},
	"px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm hover:bg-blue-200 transition-colors": twerge.CacheValue{
		Generated: "tw-38",
		Merged:    "text-sm hover:bg-blue-200 rounded-full px-3 py-1 text-blue-700 transition-colors bg-blue-100",
	},
	"space-y-12": twerge.CacheValue{
		Generated: "tw-11",
		Merged:    "space-y-12",
	},
	"space-y-6": twerge.CacheValue{
		Generated: "tw-27",
		Merged:    "space-y-6",
	},
	"text-2xl font-bold text-blue-600": twerge.CacheValue{
		Generated: "tw-49",
		Merged:    "text-2xl font-bold text-blue-600",
	},
	"text-2xl font-bold text-gray-900 mb-2": twerge.CacheValue{
		Generated: "tw-7",
		Merged:    "font-bold text-gray-900 mb-2 text-2xl",
	},
	"text-3xl font-bold text-gray-900 mb-3": twerge.CacheValue{
		Generated: "tw-13",
		Merged:    "text-3xl font-bold text-gray-900 mb-3",
	},
	"text-4xl font-bold text-gray-900 mb-2": twerge.CacheValue{
		Generated: "tw-32",
		Merged:    "text-4xl font-bold text-gray-900 mb-2",
	},
	"text-4xl font-bold text-gray-900 mb-6": twerge.CacheValue{
		Generated: "tw-19",
		Merged:    "mb-6 text-4xl font-bold text-gray-900",
	},
	"text-4xl font-bold text-gray-900 mb-8": twerge.CacheValue{
		Generated: "tw-10",
		Merged:    "font-bold text-gray-900 mb-8 text-4xl",
	},
	"text-5xl font-bold text-gray-900 mb-4": twerge.CacheValue{
		Generated: "tw-1",
		Merged:    "text-5xl font-bold text-gray-900 mb-4",
	},
	"text-blue-600 hover:text-blue-800 font-medium": twerge.CacheValue{
		Generated: "tw-9",
		Merged:    "text-blue-600 hover:text-blue-800 font-medium",
	},
	"text-blue-600 hover:text-blue-800": twerge.CacheValue{
		Generated: "tw-62",
		Merged:    "hover:text-blue-800 text-blue-600",
	},
	"text-center mb-12": twerge.CacheValue{
		Generated: "tw-0",
		Merged:    "text-center mb-12",
	},
	"text-gray-600 hover:text-blue-600 transition-colors": twerge.CacheValue{
		Generated: "tw-60",
		Merged:    "text-gray-600 hover:text-blue-600 transition-colors",
	},
	"text-gray-600 mb-4": twerge.CacheValue{
		Generated: "tw-8",
		Merged:    "text-gray-600 mb-4",
	},
	"text-gray-600 mb-8": twerge.CacheValue{
		Generated: "tw-26",
		Merged:    "text-gray-600 mb-8",
	},
	"text-gray-600 mt-1": twerge.CacheValue{
		Generated: "tw-24",
		Merged:    "text-gray-600 mt-1",
	},
	"text-gray-600": twerge.CacheValue{
		Generated: "tw-58",
		Merged:    "text-gray-600",
	},
	"text-gray-700 mb-4": twerge.CacheValue{
		Generated: "tw-17",
		Merged:    "text-gray-700 mb-4",
	},
	"text-lg font-bold mb-4": twerge.CacheValue{
		Generated: "tw-36",
		Merged:    "text-lg font-bold mb-4",
	},
	"text-sm text-gray-600 mt-1": twerge.CacheValue{
		Generated: "tw-43",
		Merged:    "text-sm text-gray-600 mt-1",
	},
	"text-xl font-semibold text-blue-600": twerge.CacheValue{
		Generated: "tw-57",
		Merged:    "text-xl font-semibold text-blue-600",
	},
	"text-xl text-gray-600 max-w-2xl mx-auto": twerge.CacheValue{
		Generated: "tw-2",
		Merged:    "text-gray-600 max-w-2xl mx-auto text-xl",
	},
	"w-12 h-12 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold": twerge.CacheValue{
		Generated: "tw-41",
		Merged:    "w-12 rounded-full flex justify-center font-bold h-12 text-white items-center bg-blue-500",
	},
	"w-16 h-16 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold text-xl": twerge.CacheValue{
		Generated: "tw-22",
		Merged:    "text-white flex text-xl w-16 items-center bg-blue-500 justify-center font-bold h-16 rounded-full",
	},
	"w-full h-48 object-cover": twerge.CacheValue{
		Generated: "tw-5",
		Merged:    "w-full h-48 object-cover",
	},
	"w-full rounded-md border border-gray-300 px-4 py-2 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:ring-opacity-20 outline-none transition-colors": twerge.CacheValue{
		Generated: "tw-29",
		Merged:    "w-full px-4 focus:ring-opacity-20 rounded-md border focus:border-blue-500 focus:ring-2 border-gray-300 py-2 outline-none transition-colors focus:ring-blue-500",
	},
}
