name: Nix Flake actions

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request:
    branches: 
      - main
      - '*'
  merge_group:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  issues: write
  packages: write

jobs:
  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux Build
            os: ubuntu-latest
            system: x86_64-linux
          - name: MacOS Build
            os: macos-latest
            system: aarch64-darwin
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: twerge
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community, devenv
      - run: nix build --accept-flake-config --no-pure-eval -L ".#devShells.${{ matrix.system }}.default"

  nix-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: twerge
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community, devenv
      - name: Build shell
        run: nix develop --accept-flake-config --no-pure-eval -c true

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: twerge
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community, devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Run a multi-line command in the devenv shell
      shell: bash
      run: |
        nix develop --no-pure-eval --accept-flake-config --command bash -c "tests"
        nix develop --no-pure-eval --accept-flake-config --command bash -c "unit-tests"
        nix develop --no-pure-eval --accept-flake-config --command bash -c "coverage-tests"
        nix develop --no-pure-eval --accept-flake-config --command bash -c "lint"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - nix-unit
      - nix-build
      - checks
    steps:
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: twerge
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community, devenv
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run build
        run: nix build -L --accept-flake-config '.#packages.x86_64-linux.doc'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./result

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: build-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      - name: Link to the GitHub Pages
        run: |
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
          echo "View the documentation at ${{ steps.deployment.outputs.page_url }}"
